name: "windows"

on: [push, pull_request]

jobs:
  LitmusAcceptance:
    runs-on: windows-2019
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install gems and puppet agent
      run: |
        bundle install
        bundle exec rake 'litmus:install_agent'
    - name: Install module
      run: |
        mkdir "C:\\ProgramData\\PuppetLabs\\code\\modules\\docker"
        echo "Copying files"
        xcopy * "C:\\ProgramData\\PuppetLabs\\code\\modules\\docker\\" /s/h/e/k/f/c/y
        echo "Puppet module list"
        puppet module list
    - name: Run acceptance tests
      run: bundle exec rake 'litmus:acceptance:localhost'     
